include_guard(GLOBAL)
include(CheckCXXCompilerFlag)


set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)


find_package(QT NAMES Qt6 Qt5 COMPONENTS Core Widgets WebSockets REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Core Widgets WebSockets  REQUIRED)


set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/target/bin)
set(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/target/lib)
set(PLUGIN_OUT_PATH ${PROJECT_BINARY_DIR}/target/plugin)
set(PROTOCOL_OUT_PATH ${PROJECT_BINARY_DIR}/target/protocol)
set(SETUP_OUTPUT_PATH ${PROJECT_BINARY_DIR}/setup)
set(SETUP_RESOURCE_PATH ${PROJECT_SOURCE_DIR}/setup/resource)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/staticlib)


set(CMAKE_ROOT_DIR ${PROJECT_SOURCE_DIR})